### ISSUE TITLE
About the error in calculating the overlap_loss function.

### ISSUE THREAD

**Issue by jdg900** [MaverickRen/PixelLM#12]
Thanks for sharing nice work.

When I ran the train_ds.py, I encountered the assertion error in https://github.com/MaverickRen/PixelLM/blob/main/model/PixelLM.py#L602, and https://github.com/MaverickRen/PixelLM/blob/main/model/PixelLM.py#L78

I updated the multi_reason_seg_dataset.py which you updated yesterday.

Error message is depicted as below:
￼
<img width="859" alt="image" src="https://github.com/MaverickRen/PixelLM/assets/46806194/b383f477-7209-4759-83a1-f1ffee327eb2">

Could you let me know what I am missing?

I’m looking forward to hearing your reply.

**Comment by MaverickRen** [comment]
Sorry, there may be problems with the overlap_loss part of the code when I organize the code. I will check it right away. You can cancel overlap_loss during training first. This still works well.

**Comment by jdg900** [comment]
Thank you for replying!

**Comment by LeyRio** [comment]
> Thank you for replying! However, even though I remove the overlap_loss, the problem still exists in https://github.com/MaverickRen/PixelLM/blob/main/model/PixelLM.py#L586 as below: ![image](https://private-user-images.githubusercontent.com/46806194/316848590-67c62535-0cb9-40c1-a2c4-d1a03454dfcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjI2NTEsIm5iZiI6MTcxNjM2MjM1MSwicGF0aCI6Ii80NjgwNjE5NC8zMTY4NDg1OTAtNjdjNjI1MzUtMGNiOS00MGMxLWEyYzQtZDFhMDM0NTRkZmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA3MTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YzVjOWU3ZWQ2YzIzMzYzNGRiZmYzMGViZTNjYzNjNzNkYzU5NzlkZThjNTEzMDkzYmE5Y2U2MDJhMjQ3YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eHgVLYwehzaQUoqfvgGaJ-RV7U79dZW_IlB5Vy1BCz4) Do you think what the cause is? I just changed config arguments and json_file_name('./dataset/muse/MUSE_train.json') in multi_reason_seg_dataset.py

Hello, I have also encountered this issue. May I ask if you have resolved this issue? What is the solution?

**Comment by zhixuanli** [comment]
Hi @jdg900 
Could you please share your solution to this issue?
Thanks!
